/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.project.kel.desktop.sarpas.view;

import com.mycompany.project.kel.desktop.sarpas.model.User;
import com.mycompany.project.kel.desktop.sarpas.util.GlobalAppState;
import java.text.SimpleDateFormat; // Import untuk format tanggal
/**
 *
 * @author AXIOO
 */
public class AdminProfilePanel extends javax.swing.JPanel {
 private User currentUser;
    /**
     * Creates new form AdminProfilePanel
     */
   public AdminProfilePanel() {
        initComponents();
        
        // Ambil data user yang sedang login
        this.currentUser = GlobalAppState.getInstance().getCurrentUser();
        
        // Tampilkan data ke form
//        loadUserData();
loadProfileData();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNamaLengkapData = new javax.swing.JLabel();
        lblUsernameData = new javax.swing.JLabel();
        lblRoleData = new javax.swing.JLabel();
        lblTempatLahirData = new javax.swing.JLabel();
        lblTanggalLahirData = new javax.swing.JLabel();
        lblAgamaData = new javax.swing.JLabel();
        lblAlamatData = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        lblNamaLengkapData.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblNamaLengkapData.setText("jLabel1");

        lblUsernameData.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblUsernameData.setText("jLabel1");

        lblRoleData.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblRoleData.setText("jLabel1");

        lblTempatLahirData.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblTempatLahirData.setText("jLabel1");

        lblTanggalLahirData.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblTanggalLahirData.setText("jLabel1");

        lblAgamaData.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblAgamaData.setText("jLabel1");

        lblAlamatData.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblAlamatData.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel1.setText("Nama Lengkap");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel2.setText("Username ");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel3.setText("Role");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel4.setText("Tempat Lahir");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel5.setText("Tanggal lahir");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel6.setText("Agama");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel7.setText("Alamat");

        jLabel8.setText(":");

        jLabel9.setText(":");

        jLabel10.setText(":");

        jLabel11.setText(":");

        jLabel12.setText(":");

        jLabel13.setText(":");

        jLabel14.setText(":");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTanggalLahirData))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTempatLahirData))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRoleData))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUsernameData))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNamaLengkapData))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAgamaData))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAlamatData)))))
                .addGap(80, 80, 80)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNamaLengkapData)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsernameData)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRoleData)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTempatLahirData)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTanggalLahirData)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgamaData)
                    .addComponent(jLabel6)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblAlamatData)
                    .addComponent(jLabel13))
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
//private void loadUserData() {
//        if (currentUser != null) {
//            // Atur teks pada JLabel yang sudah Anda buat di mode Design
//            // Pastikan nama variabelnya sesuai
//            lblNamaLengkapData.setText(currentUser.getNamaLengkap());
//            lblUsernameData.setText( currentUser.getUsername());
//            lblRoleData.setText(currentUser.getRole());
//            
//            // Menampilkan data tambahan
//            lblTempatLahirData.setText( currentUser.getTempatLahir());
//            
//            // Format tanggal agar lebih mudah dibaca
//            if (currentUser.getTanggalLahir() != null) {
//                SimpleDateFormat formatter = new SimpleDateFormat("dd MMMM yyyy");
//                lblTanggalLahirData.setText( formatter.format(currentUser.getTanggalLahir()));
//            } else {
//                lblTanggalLahirData.setText(": -");
//            }
//            
//            lblAgamaData.setText(currentUser.getAgama());
//            lblAlamatData.setText( currentUser.getAlamat());
//            
//        } else {
//            // Jika karena suatu alasan data user tidak ada
//            lblNamaLengkapData.setText(": Data tidak ditemukan");
//            lblUsernameData.setText(": Data tidak ditemukan");
//            lblRoleData.setText(": Data tidak ditemukan");
//            lblTempatLahirData.setText(": Data tidak ditemukan");
//            lblTanggalLahirData.setText(": Data tidak ditemukan");
//            lblAgamaData.setText(": Data tidak ditemukan");
//            lblAlamatData.setText(": Data tidak ditemukan");
//        }
//    }


private void loadProfileData() {
        User currentUser = GlobalAppState.getInstance().getCurrentUser();
        if (currentUser != null) {
            System.out.println("DEBUG - SiswaProfilePanel: Memuat data profil untuk user: " + currentUser.getUsername());
            
            // --- ISI SETIAP LABEL DENGAN DATA DARI currentUser ---
            // Gunakan operator ternary untuk menampilkan "-" jika data null
            if (lblNamaLengkapData != null) lblNamaLengkapData.setText(currentUser.getNamaLengkap() != null ? currentUser.getNamaLengkap() : "-");
            if (lblUsernameData != null) lblUsernameData.setText(currentUser.getUsername() != null ? currentUser.getUsername() : "-");
            if (lblRoleData != null) lblRoleData.setText(currentUser.getRole() != null ? currentUser.getRole() : "-"); 
            if (lblTempatLahirData != null) lblTempatLahirData.setText(currentUser.getTempatLahir() != null ? currentUser.getTempatLahir() : "-"); 
          
            if (lblTanggalLahirData != null) lblTanggalLahirData.setText(currentUser.getTanggalLahir() != null ? currentUser.getTanggalLahir().toString() : "-");
            if (lblAgamaData != null) lblAgamaData.setText(currentUser.getAgama() != null ? currentUser.getAgama() : "-");
            if (lblAlamatData != null) lblAlamatData.setText(currentUser.getAlamat() != null ? currentUser.getAlamat() : "-");
           
            // Atribut lain yang tidak ada di DB Anda (seperti Email, Kontak_Telepon, Kelas, NIP, dll.)
            // tidak akan bisa diisi dan harus dihapus dari desain dan kode jika tidak relevan.
            // if (lblEmailValue != null) lblEmailValue.setText(currentUser.getEmail() != null ? currentUser.getEmail() : "-");
            // if (lblKontakTeleponValue != null) lblKontakTeleponValue.setText(currentUser.getKontakTelepon() != null ? currentUser.getKontakTelepon() : "-");
            // if (lblKelasValue != null) lblKelasValue.setText(currentUser.getKelas() != null ? currentUser.getKelas() : "-");

        } else {
            System.err.println("ERROR - SiswaProfilePanel: User tidak ditemukan di GlobalAppState.");
            if (lblNamaLengkapData != null) lblNamaLengkapData.setText("Data tidak tersedia.");
        }
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAgamaData;
    private javax.swing.JLabel lblAlamatData;
    private javax.swing.JLabel lblNamaLengkapData;
    private javax.swing.JLabel lblRoleData;
    private javax.swing.JLabel lblTanggalLahirData;
    private javax.swing.JLabel lblTempatLahirData;
    private javax.swing.JLabel lblUsernameData;
    // End of variables declaration//GEN-END:variables
}
