/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.project.kel.desktop.sarpas.view;

import com.mycompany.project.kel.desktop.sarpas.model.Barang;
import com.mycompany.project.kel.desktop.sarpas.dao.BarangDAO;
import java.awt.Font; // Untuk font (opsional)
import javax.swing.JPanel;

import javax.swing.JTable;      // Diperlukan untuk tabel
import javax.swing.table.DefaultTableModel; // Diperlukan untuk model tabel
import javax.swing.JLabel;      // Untuk label (jika ada di desain)
import javax.swing.BoxLayout;   // Untuk layout jika pakai ini
import java.awt.BorderLayout;   // Untuk layout utama panel
import java.awt.FlowLayout;     // Untuk layout panel top

import java.util.List;
import java.awt.Color; // Jika Color diperlukan


import java.util.List;
import java.awt.Color;
/**
 *
 * @author AXIOO
 */
public class InventarisSiswaPanel extends javax.swing.JPanel {
 
     private DefaultTableModel tableModel; // Variabel kelas untuk model tabel
    private BarangDAO barangDAO; // Objek 
    /**
     * Creates new form InventarisSiswaPanel
     */
    public InventarisSiswaPanel() {
         initComponents(); // Ini memanggil kode yang dihasilkan GUI Builder
        
        System.out.println("DEBUG - InventarisSiswaPanel: Constructor dimulai."); 
        
        this.barangDAO = new BarangDAO(); // Inisialisasi DAO

        // --- INI BARIS KRUSIAL UNTUK MENGHUBUNGKAN tableModel ---
        // tableModel akan mengambil model yang sudah diatur oleh initComponents()
        // Pastikan nama JTable Anda di Design Mode adalah 'tblInventaris' (huruf 'I' besar)
        tableModel = (DefaultTableModel) tblInventaris.getModel(); 
        
        System.out.println("DEBUG - InventarisSiswaPanel: tableModel berhasil dihubungkan. Jumlah kolom: " + tableModel.getColumnCount());

        loadBarangData(); // Muat data barang dari database
        System.out.println("DEBUG - InventarisSiswaPanel: loadBarangData() selesai.");
        
        // setupRoleBasedAccess() tidak lagi diperlukan di sini karena tidak ada tombol untuk diatur
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventaris = new javax.swing.JTable();

        tblInventaris.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama barang", "ID Kategori", "Kode Barang", "Jumlah Total", "Kondisi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblInventaris);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

  
  
  
   public void loadBarangData() {
        tableModel.setRowCount(0); // Bersihkan baris yang ada
        
        System.out.println("DEBUG - loadBarangData: Memanggil barangDAO.getAllBarang()...");
        List<Barang> daftarBarang = barangDAO.getAllBarang(); 

        if (daftarBarang != null) {
            System.out.println("DEBUG - loadBarangData: Jumlah barang dari DB: " + daftarBarang.size());
            if (!daftarBarang.isEmpty()) {
                for (Barang barang : daftarBarang) {
                    tableModel.addRow(new Object[]{
                        // Tambahkan data sesuai dengan 5 KOLOM HEADER di atas
                        // Urutan harus sesuai dengan header: Nama barang, ID Kategori, Kode Barang, Jumlah Total, Kondisi
                        barang.getNamaBarang(),     // 1. Nama barang
                        barang.getIdKategori(),     // 2. ID Kategori
                        barang.getKodeBarang(),     // 3. Kode Barang
                        barang.getJumlahTotal(),    // 4. Jumlah Total
                        barang.getKondisi()         // 5. Kondisi
                    });
                }
                System.out.println("DEBUG - loadBarangData: " + tableModel.getRowCount() + " baris ditambahkan ke tabel.");
            } else {
                System.out.println("DEBUG - loadBarangData: Database mengembalikan daftar barang kosong.");
            }
        } else {
            System.out.println("DEBUG - loadBarangData: barangDAO.getAllBarang() mengembalikan NULL.");
        }
    }
                    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInventaris;
    // End of variables declaration//GEN-END:variables
}
