/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.project.kel.desktop.sarpas.view;

import com.mycompany.project.kel.desktop.sarpas.dao.BarangDAO;
import com.mycompany.project.kel.desktop.sarpas.dao.PemeliharaanDAO;
import com.mycompany.project.kel.desktop.sarpas.dao.UserDAO;
import com.mycompany.project.kel.desktop.sarpas.model.Barang;
import com.mycompany.project.kel.desktop.sarpas.model.Pemeliharaan;
import com.mycompany.project.kel.desktop.sarpas.model.User;
import com.mycompany.project.kel.desktop.sarpas.util.GlobalAppState;
import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author AXIOO
 */
public class JadwalPerawatanPanel extends javax.swing.JPanel {
 private PemeliharaanDAO pemeliharaanDAO;
    private DefaultTableModel tableModel;
    private int selectedPemeliharaanId = -1;
    /**
     * Creates new form JadwalPerawatanPanel
     */
    public JadwalPerawatanPanel() {
        initComponents();
        
        this.pemeliharaanDAO = new PemeliharaanDAO();
        this.tableModel = (DefaultTableModel) tblPerawatan.getModel();
        
        setupComboBox();
        loadPerawatanData();
        setupListeners();
          loadComboBoxData();
           setupRoleBasedUI();
        // Awalnya, tombol update dinonaktifkan
        btnUpdateStatus.setEnabled(false);
        comboStatus.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPerawatan = new javax.swing.JTable();
        panelTambahJadwal = new javax.swing.JPanel();
        comboBarang = new javax.swing.JComboBox<>();
        comboPetugas = new javax.swing.JComboBox<>();
        txtJenisPerawatan = new javax.swing.JTextField();
        txtTanggalJadwal = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCatatan = new javax.swing.JTextArea();
        btnTambahJadwal = new com.mycompany.project.kel.desktop.sarpas.view.RoundedButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboStatus = new javax.swing.JComboBox<>();
        btnUpdateStatus = new com.mycompany.project.kel.desktop.sarpas.view.RoundedButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblPerawatan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblPerawatan.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tblPerawatan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Pemeliharaan", "Tanggal Jadwal", "Nama Barang", "Nama Petugas", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblPerawatan);

        panelTambahJadwal.setBackground(new java.awt.Color(255, 255, 255));

        comboBarang.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        comboBarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        comboBarang.setMaximumSize(new java.awt.Dimension(72, 22));

        comboPetugas.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        comboPetugas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        comboPetugas.setMaximumSize(new java.awt.Dimension(72, 22));

        txtJenisPerawatan.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        txtJenisPerawatan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtJenisPerawatan.setMaximumSize(new java.awt.Dimension(72, 22));
        txtJenisPerawatan.setMinimumSize(new java.awt.Dimension(72, 22));
        txtJenisPerawatan.setPreferredSize(new java.awt.Dimension(72, 22));

        txtTanggalJadwal.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        txtTanggalJadwal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTanggalJadwal.setMaximumSize(new java.awt.Dimension(72, 22));
        txtTanggalJadwal.setMinimumSize(new java.awt.Dimension(72, 22));
        txtTanggalJadwal.setPreferredSize(new java.awt.Dimension(72, 22));

        txtCatatan.setColumns(20);
        txtCatatan.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtCatatan.setRows(5);
        txtCatatan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(txtCatatan);

        btnTambahJadwal.setBackground(new java.awt.Color(0, 153, 204));
        btnTambahJadwal.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnTambahJadwal.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahJadwal.setText("Tambah Jadwal");
        btnTambahJadwal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel1.setText("Nama Barang");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel2.setText("Petugas");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel3.setText("Tanggal Jadwal");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel4.setText("Jelaskan Jenis perawatan");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Catatan");

        javax.swing.GroupLayout panelTambahJadwalLayout = new javax.swing.GroupLayout(panelTambahJadwal);
        panelTambahJadwal.setLayout(panelTambahJadwalLayout);
        panelTambahJadwalLayout.setHorizontalGroup(
            panelTambahJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTambahJadwalLayout.createSequentialGroup()
                .addGroup(panelTambahJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTambahJadwalLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelTambahJadwalLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(panelTambahJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(panelTambahJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTambahJadwalLayout.createSequentialGroup()
                                .addComponent(comboPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addGroup(panelTambahJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelTambahJadwalLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel3))
                                    .addComponent(txtTanggalJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelTambahJadwalLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2)))
                        .addGroup(panelTambahJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTambahJadwalLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel4))
                            .addGroup(panelTambahJadwalLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(txtJenisPerawatan, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(panelTambahJadwalLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(btnTambahJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTambahJadwalLayout.setVerticalGroup(
            panelTambahJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTambahJadwalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTambahJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(panelTambahJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTanggalJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJenisPerawatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTambahJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(13, 13, 13)
                .addGroup(panelTambahJadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        comboStatus.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        comboStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboStatusActionPerformed(evt);
            }
        });

        btnUpdateStatus.setBackground(new java.awt.Color(0, 153, 204));
        btnUpdateStatus.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnUpdateStatus.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateStatus.setText("Update Status");
        btnUpdateStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setText("Jadwal Perawatan Mendatang");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelTambahJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 109, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnUpdateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(panelTambahJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(259, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboStatusActionPerformed

     private void setupRoleBasedUI() {
        String role = GlobalAppState.getInstance().getCurrentUser().getRole();
        
        // Jika yang login adalah Teknisi
        if ("teknisi".equalsIgnoreCase(role)) {
            // Sembunyikan seluruh panel untuk menambah jadwal
            panelTambahJadwal.setVisible(false);
        }
        // Jika Admin, panel akan terlihat secara default
        
        // Atur kondisi awal form update
        btnUpdateStatus.setEnabled(false);
        comboStatus.setEnabled(false);
    }
    
    
        private void setupComboBox() {
        comboStatus.removeAllItems();
        comboStatus.addItem("Terjadwal");
        comboStatus.addItem("Sedang Dikerjakan");
        comboStatus.addItem("Selesai");
    }

         private void loadComboBoxData() {
        // Mengisi ComboBox untuk form tambah jadwal
        BarangDAO barangDAO = new BarangDAO();
        List<Barang> daftarBarang = barangDAO.getAllBarang();
        for (Barang b : daftarBarang) {
            comboBarang.addItem(b);
        }
        
        UserDAO userDAO = new UserDAO();
        List<User> daftarUser = userDAO.getAllUsers(); // Asumsi ada metode ini di UserDAO
        for (User u : daftarUser) {
            // Hanya tambahkan admin atau teknisi sebagai pilihan petugas
            if("admin".equalsIgnoreCase(u.getRole()) || "teknisi".equalsIgnoreCase(u.getRole())) {
                comboPetugas.addItem(u);
            }
        }
    }
        
        
        private void loadPerawatanData() {
        tableModel.setRowCount(0);
        List<Pemeliharaan> daftarJadwal = pemeliharaanDAO.getAllPemeliharaan();
        for (Pemeliharaan p : daftarJadwal) {
            tableModel.addRow(new Object[]{
                p.getIdPemeliharaan(),
                p.getTanggalJadwal(),
                p.getNamaBarang(),
                p.getNamaPetugas(),
                p.getStatus()
            });
        }
    }
        
        private void setupListeners() {
        // Listener untuk memilih baris di tabel (untuk update status)
        tblPerawatan.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && tblPerawatan.getSelectedRow() != -1) {
                int selectedRow = tblPerawatan.getSelectedRow();
                selectedPemeliharaanId = (int) tableModel.getValueAt(selectedRow, 0);
                String currentStatus = tableModel.getValueAt(selectedRow, 4).toString();
                comboStatus.setSelectedItem(currentStatus);
                btnUpdateStatus.setEnabled(true);
                comboStatus.setEnabled(true);
            }
        });

        // Listener untuk tombol update status
        btnUpdateStatus.addActionListener(e -> updateStatusJadwal());
        
        // Listener untuk tombol tambah jadwal (hanya akan bisa diklik oleh Admin)
        btnTambahJadwal.addActionListener(e -> tambahJadwalBaru());
    }
        
            private void updateStatusJadwal() {
        if (selectedPemeliharaanId == -1) {
            JOptionPane.showMessageDialog(this, "Pilih jadwal yang ingin diupdate.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String newStatus = comboStatus.getSelectedItem().toString();
        boolean success = pemeliharaanDAO.updateStatusPemeliharaan(selectedPemeliharaanId, newStatus);
        if (success) {
            JOptionPane.showMessageDialog(this, "Status berhasil diupdate.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            loadPerawatanData();
            resetUpdateForm();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal mengupdate status.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
            
            private void tambahJadwalBaru() {
        try {
            Barang selectedBarang = (Barang) comboBarang.getSelectedItem();
            User selectedPetugas = (User) comboPetugas.getSelectedItem();
            Date tanggal = Date.valueOf(txtTanggalJadwal.getText()); // Format YYYY-MM-DD
            
            Pemeliharaan p = new Pemeliharaan();
            p.setIdBarang(selectedBarang.getIdBarang());
            p.setIdPetugas(selectedPetugas.getIdUsers()); // Pastikan nama getter ID user benar
            p.setTanggalJadwal(tanggal);
            p.setJenisPerawatan(txtJenisPerawatan.getText());
            p.setCatatanTambahan(txtCatatan.getText());
            
            boolean success = pemeliharaanDAO.addPemeliharaan(p);
            if(success) {
                JOptionPane.showMessageDialog(this, "Jadwal baru berhasil ditambahkan.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                loadPerawatanData();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menambahkan jadwal.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Input tidak valid. Pastikan format tanggal YYYY-MM-DD.", "Error Input", JOptionPane.ERROR_MESSAGE);
        }
    }  
        
        
       private void resetUpdateForm() {
        tblPerawatan.clearSelection();
        selectedPemeliharaanId = -1;
        btnUpdateStatus.setEnabled(false);
        comboStatus.setEnabled(false);
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTambahJadwal;
    private javax.swing.JButton btnUpdateStatus;
    private javax.swing.JComboBox<Barang> comboBarang;
    private javax.swing.JComboBox<User> comboPetugas;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelTambahJadwal;
    private javax.swing.JTable tblPerawatan;
    private javax.swing.JTextArea txtCatatan;
    private javax.swing.JTextField txtJenisPerawatan;
    private javax.swing.JTextField txtTanggalJadwal;
    // End of variables declaration//GEN-END:variables
}
