/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.project.kel.desktop.sarpas.view;

import com.mycompany.project.kel.desktop.sarpas.dao.PemeliharaanDAO;
import com.mycompany.project.kel.desktop.sarpas.model.Pemeliharaan;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AXIOO
 */
public class RiwayatPerawatanPanel extends javax.swing.JPanel {
 private PemeliharaanDAO pemeliharaanDAO;
    private DefaultTableModel tableModel;
    /**
     * Creates new form RiwayatPerawatanPanel
     */
    public RiwayatPerawatanPanel() {
        initComponents();
         this.pemeliharaanDAO = new PemeliharaanDAO();
        this.tableModel = (DefaultTableModel) tblRiwayatPerawatan.getModel();
        
        setupComboBoxFilter();
        loadRiwayatData();
        setupListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRiwayatPerawatan = new javax.swing.JTable();
        txtCariRiwayat = new javax.swing.JTextField();
        comboFilterStatus = new javax.swing.JComboBox<>();
        btnFilter = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tblRiwayatPerawatan.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        tblRiwayatPerawatan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Pemeliharaan", "Tanggal Jadwal", "Tanggal Selesai", "Nama Barang", "Kode Barang", "Nama Petugas", "Status", "Catatan Tambahan"
            }
        ));
        jScrollPane1.setViewportView(tblRiwayatPerawatan);

        txtCariRiwayat.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        txtCariRiwayat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        comboFilterStatus.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        comboFilterStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnFilter.setBackground(new java.awt.Color(204, 204, 204));
        btnFilter.setIcon(new javax.swing.ImageIcon("C:\\Users\\AXIOO\\Documents\\NetBeansProjects\\Project-kel-6-desktop-sarpas\\src\\main\\java\\img\\img\\iconcari.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(txtCariRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboFilterStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCariRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboFilterStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

      private void setupComboBoxFilter() {
        comboFilterStatus.removeAllItems();
        comboFilterStatus.addItem("Semua");
        comboFilterStatus.addItem("Terjadwal");
        comboFilterStatus.addItem("Sedang Dikerjakan");
        comboFilterStatus.addItem("Selesai");
    }
    
        private void loadRiwayatData() {
        
        String keyword = txtCariRiwayat.getText();
        String status = comboFilterStatus.getSelectedItem().toString();
        
        tableModel.setRowCount(0); 
        
       
        List<Pemeliharaan> daftarJadwal = pemeliharaanDAO.getFilteredPemeliharaan(keyword, status);
        
        // Isi tabel dengan 8 kolom data
        for (Pemeliharaan p : daftarJadwal) {
            tableModel.addRow(new Object[]{
                p.getIdPemeliharaan(),
                p.getTanggalJadwal(),
                p.getTanggalSelesai(),
                p.getNamaBarang(),
                p.getKodeBarang(),
                p.getNamaPetugas(),
                p.getStatus(),
                p.getCatatanTambahan()
            });
        }
    }
      
       private void setupListeners() {
      
        btnFilter.addActionListener(e -> loadRiwayatData());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilter;
    private javax.swing.JComboBox<String> comboFilterStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRiwayatPerawatan;
    private javax.swing.JTextField txtCariRiwayat;
    // End of variables declaration//GEN-END:variables
}
