/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.project.kel.desktop.sarpas.view;

import com.mycompany.project.kel.desktop.sarpas.dao.PeminjamanDAO;
import com.mycompany.project.kel.desktop.sarpas.model.Peminjaman;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author AXIOO
 */
public class RiwayatPeminjamanPanel extends javax.swing.JPanel {
  private PeminjamanDAO peminjamanDAO;
    private DefaultTableModel tableModel;
    private int selectedPeminjamanId = -1;
    /**
     * Creates new form RiwayatPeminjamanPanel
     */
    public RiwayatPeminjamanPanel() {
        initComponents(); // Panggilan standar dari NetBeans

        this.peminjamanDAO = new PeminjamanDAO();
        this.tableModel = (DefaultTableModel) tblPeminjaman.getModel();

        loadPeminjamanData();
        setupListeners();
        updateButtonState(false); // Awalnya tombol non-aktif
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnSetujui = new com.mycompany.project.kel.desktop.sarpas.view.RoundedButton();
        btnTolak = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtKeperluan = new javax.swing.JTextArea();
        btnKembali = new com.mycompany.project.kel.desktop.sarpas.view.RoundedButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPeminjaman = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnSetujui.setBackground(new java.awt.Color(0, 153, 204));
        btnSetujui.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnSetujui.setForeground(new java.awt.Color(255, 255, 255));
        btnSetujui.setText("Setujui");
        btnSetujui.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnTolak.setBackground(new java.awt.Color(0, 153, 204));
        btnTolak.setForeground(new java.awt.Color(255, 255, 255));
        btnTolak.setText("Tolak");
        btnTolak.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtKeperluan.setEditable(false);
        txtKeperluan.setColumns(20);
        txtKeperluan.setRows(5);
        txtKeperluan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(txtKeperluan);

        btnKembali.setBackground(new java.awt.Color(0, 153, 204));
        btnKembali.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali.setText("Sudah dikembalikan");
        btnKembali.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel1.setText("Keperluan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnTolak, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnSetujui, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(btnSetujui, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTolak, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblPeminjaman.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tblPeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Peminjam", "Nama Peminjam", "Nama Barang", "Tanggal Pinjam", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPeminjaman);

        jScrollPane3.setViewportView(jScrollPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
 private void loadPeminjamanData() {
        tableModel.setRowCount(0); // Kosongkan tabel

        List<Peminjaman> daftarPeminjaman = peminjamanDAO.getAllPeminjaman();

        for (Peminjaman p : daftarPeminjaman) {
            // Tambahkan baris baru ke tabel
            tableModel.addRow(new Object[]{
                 p.getIdPeminjaman(),
                 p.getNamaPeminjam(),
                   p.getNamaFasilitasManual(), 
                p.getTanggalPeminjaman(),
                p.getStatusPeminjaman()
            });
        }
    }
 
 
private void setupListeners() {
    // Listener untuk JTable, aktif saat baris dipilih
    tblPeminjaman.getSelectionModel().addListSelectionListener(e -> {
        // ... (try-catch block Anda tetap di sini) ...
        if (!e.getValueIsAdjusting() && tblPeminjaman.getSelectedRow() != -1) {
            int selectedRow = tblPeminjaman.getSelectedRow();
            
            // Ambil ID dari kolom 0
            selectedPeminjamanId = (int) tableModel.getValueAt(selectedRow, 0);

            // Ambil STATUS dari kolom terakhir (indeks 4) untuk logika tombol
            String status = tableModel.getValueAt(selectedRow, 4).toString();

            // Ambil detail keperluan untuk ditampilkan di JTextArea
            Peminjaman selectedPeminjaman = getSelectedPeminjamanFromList(selectedPeminjamanId);
            if (selectedPeminjaman != null) {
                txtKeperluan.setText(selectedPeminjaman.getKeperluan());
            }

            // Logika untuk mengaktifkan tombol yang sesuai
            if ("Menunggu Persetujuan".equalsIgnoreCase(status)) {
                btnSetujui.setEnabled(true);
                btnTolak.setEnabled(true);
                btnKembali.setEnabled(false);
            } else if ("Disetujui".equalsIgnoreCase(status)) {
                btnSetujui.setEnabled(false);
                btnTolak.setEnabled(false);
                btnKembali.setEnabled(true);
            } else { // Jika statusnya "Ditolak" atau "Sudah Dikembalikan"
                btnSetujui.setEnabled(false);
                btnTolak.setEnabled(false);
                btnKembali.setEnabled(false);
            }
        }
    });

    // Listener untuk tombol "Setujui"
    btnSetujui.addActionListener(e -> updateStatus("Disetujui"));

    // Listener untuk tombol "Tolak"
    btnTolak.addActionListener(e -> updateStatus("Ditolak"));
    
    // --- TAMBAHKAN LISTENER UNTUK TOMBOL BARU ---
    btnKembali.addActionListener(e -> updateStatus("Sudah Dikembalikan"));
}

   private Peminjaman getSelectedPeminjamanFromList(int id) {
        List<Peminjaman> daftarPeminjaman = peminjamanDAO.getAllPeminjaman();
        for(Peminjaman p : daftarPeminjaman) {
            if(p.getIdPeminjaman() == id) {
                return p;
            }
        }
        return null;
    }
 
    /**
     * Mengupdate status peminjaman di database.
     * @param newStatus Status baru ("Disetujui" atau "Ditolak").
     */
    private void updateStatus(String newStatus) {
        if (selectedPeminjamanId == -1) {
            JOptionPane.showMessageDialog(this, "Pilih sebuah data peminjaman terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean success = peminjamanDAO.updateStatusPeminjaman(selectedPeminjamanId, newStatus);

        if (success) {
            JOptionPane.showMessageDialog(this, "Status peminjaman berhasil diubah menjadi '" + newStatus + "'.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            loadPeminjamanData(); // Muat ulang tabel
            resetFormState();    // Kembalikan form ke kondisi awal
        } else {
            JOptionPane.showMessageDialog(this, "Gagal mengupdate status peminjaman.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Mengaktifkan atau menonaktifkan tombol aksi.
     */
    // Perbarui metode updateButtonState
private void updateButtonState(boolean enabled) {
    btnSetujui.setEnabled(enabled);
    btnTolak.setEnabled(enabled);
    btnKembali.setEnabled(enabled); // <-- Tambahkan ini
}

// Perbarui metode resetFormState
private void resetFormState() {
    tblPeminjaman.clearSelection();
    txtKeperluan.setText("");
    selectedPeminjamanId = -1;
    // Atur semua tombol ke non-aktif saat form di-reset
    btnSetujui.setEnabled(false);
    btnTolak.setEnabled(false);
    btnKembali.setEnabled(false);
}
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSetujui;
    private javax.swing.JButton btnTolak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblPeminjaman;
    private javax.swing.JTextArea txtKeperluan;
    // End of variables declaration//GEN-END:variables
}
