/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.project.kel.desktop.sarpas.view;

import com.mycompany.project.kel.desktop.sarpas.model.User;
import com.mycompany.project.kel.desktop.sarpas.util.GlobalAppState;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.BoxLayout; // Import BoxLayout
import javax.swing.BorderFactory; // Import BorderFactory
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.Dimension;
import java.awt.Color;
import java.awt.Font;
/**
 *
 * @author AXIOO
 */
public class SidebarPanel extends javax.swing.JPanel {

    /**
     * Creates new form SidebarPanel
     */
    public SidebarPanel() {
        initComponents(); // Ini memanggil kode yang dihasilkan GUI Builder

        // --- Pengaturan Tampilan Dasar Panel Sidebar ---
       setBackground(Color.WHITE);
        setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY, 1));

    if (btnProfile != null) btnProfile.addActionListener(e -> fireButtonAction(e.getActionCommand())); // Tambahkan ini
        // Tambahkan ActionListener ke setiap tombol yang Anda buat di Design Mode
        // PASTIKAN NAMA VARIABEL TOMBOL DI SINI SAMA DENGAN YANG ANDA ATUR DI DESIGN MODE!
        if (btnDashboard != null) btnDashboard.addActionListener(e -> fireButtonAction(e.getActionCommand()));
        if (btnInventaris != null) btnInventaris.addActionListener(e -> fireButtonAction(e.getActionCommand()));
        if (btnPeminjaman != null) btnPeminjaman.addActionListener(e -> fireButtonAction(e.getActionCommand()));
        if (btnLaporan != null) btnLaporan.addActionListener(e -> fireButtonAction(e.getActionCommand())); // Hapus baris ini jika btnLaporan tidak ada
     

        // Panggil metode untuk mengatur visibilitas awal (saat panel dibuat)
        updateButtonVisibility();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDashboard = new javax.swing.JButton();
        btnInventaris = new javax.swing.JButton();
        btnPeminjaman = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();

        btnDashboard.setText("Dashboard");

        btnInventaris.setText("Inventaris Barang");
        btnInventaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarisActionPerformed(evt);
            }
        });

        btnPeminjaman.setText("Peminjaman Fasilitas");

        btnLaporan.setText("Laporan Kerusakan");

        btnProfile.setText("Profile");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInventaris, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(562, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btnProfile)
                .addGap(30, 30, 30)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnInventaris, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnPeminjaman)
                .addGap(33, 33, 33)
                .addComponent(btnLaporan)
                .addContainerGap(211, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
 public void setButtonActionListener(ActionListener listener) {
        this.buttonActionListener = listener;
    }
 private void fireButtonAction(String command) {
        if (buttonActionListener != null) {
            buttonActionListener.actionPerformed(new ActionEvent(this, ActionEvent.ACTION_PERFORMED, command));
        }
    }
    private void btnInventarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInventarisActionPerformed
  public void updateButtonVisibility() {
        boolean isLoggedIn = GlobalAppState.getInstance().getCurrentUser() != null;
        boolean isAdmin = GlobalAppState.getInstance().isAdmin();
        boolean isTeknisi = GlobalAppState.getInstance().isTeknisi();
        boolean isGuru = GlobalAppState.getInstance().isGuru();
        boolean isSiswa = GlobalAppState.getInstance().isSiswa();

        System.out.println("DEBUG - SidebarPanel RBAC: updateButtonVisibility dipanggil.");
        System.out.println("  Is Logged In: " + isLoggedIn);
        System.out.println("  Is Admin: " + isAdmin);
        System.out.println("  Is Teknisi: " + isTeknisi);
        System.out.println("  Is Guru: " + isGuru);
        System.out.println("  Is Siswa: " + isSiswa);


        // Sembunyikan semua secara default jika belum login
         if (!isLoggedIn) {
            if (btnDashboard != null) btnDashboard.setVisible(false);
            if (btnInventaris != null) btnInventaris.setVisible(false);
            if (btnPeminjaman != null) btnPeminjaman.setVisible(false);
            if (btnLaporan != null) btnLaporan.setVisible(false); 
           if (btnProfile != null) btnProfile.setVisible(false); // Tambahkan ini
        
            System.out.println("  DEBUG - SidebarPanel: Tidak login, semua tombol disembunyikan.");
            return;
        }
 if (btnProfile != null) {
        btnProfile.setVisible(isAdmin || isTeknisi || isGuru || isSiswa); // Semua peran bisa melihat profilnya
        // Atau hanya Siswa/Guru: btnProfile.setVisible(isSiswa || isGuru);
        System.out.println("  DEBUG - SidebarPanel: Profil setVisible(" + (isAdmin || isTeknisi || isGuru || isSiswa) + ")."); // Tambahkan ini
    }
        // Atur visibilitas berdasarkan peran
        if (btnDashboard != null) {
            btnDashboard.setVisible(true); // Dashboard selalu terlihat setelah login
            System.out.println("  DEBUG - SidebarPanel: Dashboard setVisible(true).");
        }

        if (btnInventaris != null) {
            btnInventaris.setVisible(isAdmin || isTeknisi || isGuru || isSiswa);
            System.out.println("  DEBUG - SidebarPanel: Inventaris setVisible(" + (isAdmin || isTeknisi || isGuru || isSiswa) + ").");
        }
        if (btnPeminjaman != null) {
            btnPeminjaman.setVisible(isAdmin || isTeknisi || isGuru || isSiswa);
            System.out.println("  DEBUG - SidebarPanel: Peminjaman setVisible(" + (isAdmin || isTeknisi || isGuru || isSiswa) + ").");
        }
        if (btnLaporan != null) { // Hapus blok if ini jika btnLaporan tidak ada
            btnLaporan.setVisible(isAdmin || isTeknisi || isGuru || isSiswa);
            System.out.println("  DEBUG - SidebarPanel: Laporan Kerusakan setVisible(" + (isAdmin || isTeknisi || isGuru || isSiswa) + ").");
        }
       
    }

 private ActionListener buttonActionListener; 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnInventaris;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnPeminjaman;
    private javax.swing.JButton btnProfile;
    // End of variables declaration//GEN-END:variables
}
