/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.project.kel.desktop.sarpas.view;

import com.mycompany.project.kel.desktop.sarpas.model.Lokasi;

/**
 *
 * @author AXIOO
 */
public class TestComboBoxFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TestComboBoxFrame.class.getName());

    /**
     * Creates new form TestComboBoxFrame
     */
    public TestComboBoxFrame() {
    initComponents(); // JANGAN DIUBAH

    // --- TAMBAHKAN KODE PENGUJIAN DI BAWAH INI ---
    System.out.println("MEMULAI TES JCOMBOBOX...");
    try {
        com.mycompany.project.kel.desktop.sarpas.dao.LokasiDAO dao = new com.mycompany.project.kel.desktop.sarpas.dao.LokasiDAO();
        java.util.List<com.mycompany.project.kel.desktop.sarpas.model.Lokasi> daftarLokasi = dao.getAllLokasi();

        if (daftarLokasi == null) {
            System.out.println("TES GAGAL: DAO mengembalikan list null.");
            return;
        }

        if (daftarLokasi.isEmpty()) {
            System.out.println("TES GAGAL: DAO mengembalikan list kosong. Cek isi tabel di database.");
        } else {
             System.out.println("TES BERHASIL: DAO mengembalikan " + daftarLokasi.size() + " data.");
        }

        for (com.mycompany.project.kel.desktop.sarpas.model.Lokasi l : daftarLokasi) {
            System.out.println("TES: Menambahkan item -> " + l); // Ini akan memanggil toString()
            comboLokasiTest.addItem(l);
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboLokasiTest = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(comboLokasiTest, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addComponent(comboLokasiTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TestComboBoxFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Lokasi> comboLokasiTest;
    // End of variables declaration//GEN-END:variables
}
